language: java

## safelist
#branches:
#  only:
#    - master

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - mvn clean package -Pdocker

  - docker build -f ./src/main/docker/Dockerfile -t $TRAVIS_REPO_SLUG:latest .
  - docker tag $TRAVIS_REPO_SLUG:latest $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER

  - docker push $TRAVIS_REPO_SLUG:latest
  - docker push $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER

notifications:
  email:
    recipients:
      - maria.ic.mihai@gmail.com
    on_success: never # default: change
    on_failure: always # default: always