version: '2'
services:
  #  database:
  #    image: postgres
  #    ports:
  #      - "5432:5432"
  #    environment:
  #      POSTGRES_USER: "postgres"
  #      POSTGRES_PASSWORD: "p0stgr@s"
  #      POSTGRES_DB: "eagle_eye_local"
  configserver:
    image: mariamihai/sma-configuration-service
    ports:
      - "8888:8888"
    env_file:
      - local.env
  licensingservice:
    image: mariamihai/sma-licensing-service
    ports:
      - "8080:8080"
    depends_on:
      - configserver
#      - database
    environment:
      SPRING_PROFILES_ACTIVE: "default"
    env_file:
      - local.env
